### ISSUE TITLE
Tutorial documentation revisions tracking issue

### ISSUE THREAD

**Issue by tedinski** [model-checking/kani#1320]
Review of existing tutorial

* [x] Review [2.1. First steps](https://model-checking.github.io/kani/tutorial-first-steps.html)
* [x] Review [2.2. Failures that Kani can spot](https://model-checking.github.io/kani/tutorial-kinds-of-failure.html)
* [x] Review [2.3. Loop unwinding](https://model-checking.github.io/kani/tutorial-loop-unwinding.html)
* [ ] Review [2.4. Nondeterministic variables](https://model-checking.github.io/kani/tutorial-nondeterministic-variables.html)
* [ ] Review [3.1. Comparison with other tools](https://model-checking.github.io/kani/tool-comparison.html)
* [ ] Review [3.2. Where to start on real code](https://model-checking.github.io/kani/tutorial-real-code.html)
* [ ] Review the getting started and installation flow

Notable problems to fix:

* [x] We should recommend `#[kani::unwind]` not `--default-unwind`.
* [x] May need to review tutorial in light of having multiple proof harnesses. Much of it was written before this was implemented.
* [ ] We should collect "real world examples" somewhere which can at least include links to our current blog posts.
* [x] Let's be more specific about debugging traces in the tutorial
* [x] Ditto debugging non-termination
* [x] We may need new content to help cover "debugging coverage" as a concept. Perhaps this can be a part of the new section on spec writing (below)
* [x] Where do we document annotations like proof/unwind/etc?
* [x] Tutorials should be about using `cargo kani` on a project, not `kani` on an individual file.
* [x] As a final polishing step, make sure we don't leave any harnesses named `main` anymore.
* [ ] `is_valid` is currently mentioned on https://model-checking.github.io/kani/undefined-behaviour.html

Possible new section to write:

* Specification writing. Perhaps "how to specify that sort works". Include minimal techniques like "nondet is forall".
* More advanced spec techniques, like object invariants.
* [ ] Add an explanation about how builds work, the need for `cfg(kani)`, the `kani` dependency, etc
