### ISSUE TITLE
Tracking issue for function and method stubbing

### ISSUE THREAD

**Issue by aaronbembenek-aws** [model-checking/kani#1809]
# Summary

This is a tracking issue for the implementation of function and method stubbing, which will enable users to swap in alternate definitions of functions and methods during verification.

During development, this feature will be gated by the unstable option `--enable-stubbing`.

# Major Steps

Suggestion of major steps:

- [x] Get feedback on the `function_stubbing` RFC.
- [x] Implement `kani::stub` attribute.
- [x] Implement `--enable-stubbing` option. This will initially require `--harness` as well.
- [x] Implement basic stubbing mechanism, requiring a single harness, and doing no path resolution for function/method names.
- [X] Implement stub validation.
- [ ] Implement path resolution for function/method names.
- [ ] Implement mechanism removing single harness requirement.
- [ ] Stabilization PR.
