### ISSUE TITLE
Tracking issue: Replacing supported features scripts with assess

### ISSUE THREAD

**Issue by tedinski** [model-checking/kani#1922]
There are a few tasks that need doing to replace the scripts ([located here](https://github.com/model-checking/kani/tree/main/scripts/exps)) for measuring unsupported features with Assess.

* [ ] Develop a JSON output format for Assess.
* [ ] #1819 is required to reproduce the same metrics we currently produce. (This is a consequence of the switch to MIR linker.)
* [ ] We should have a new mode for measuring unsupported features only. (As opposed to the current goal for assess, of running tests under Kani. To reproduce the current behavior we only need build information, not test running results. We'll want those later.)
* [ ] The reachability mode needs changing as well. We should treat public functions as roots and NOT build in test mode for this.
* [ ] We should produce a real aggregator that runs assess on all targets, reads the json outputs, and outputs aggregate results.
* [ ] Finally, we should run this nightly.

Over time I suspect we'll want to experiment with the mode changing behaviors, to move towards more useful metrics than the current ones we're tracking. But to start we need to reproduce our current metrics, then starting changing things. So I suspect we'll want all of (codegen only, tests mode, pubfns/test fns) to be flags we can turn on/off.
