### ISSUE TITLE
Tracking issue: Improving Assess for analyzing many crates

### ISSUE THREAD

**Issue by tedinski** [model-checking/kani#2138]
This issue is meant to document improvements I think would be helpful after trying out assess in the wild:

Two new tables would be helpful:

* [ ] #2058 - Presently you need to look through the log output, which is not hard, but it requires effort for something that should be easily summarizable. Further, I think it'd be cool if we can link known ones to open issues on our repo. :)
* [ ] #1819 - The second half. We now see `unsupported_construct` get hit by tests, so we really need the unsupported features table to have columns for features actually hit by tests and sort according to that data.
* [ ] The "successful tests" table could be aggregated by file. When I had a lot of results (600+ tests) ignoring the tests themselves and looking at the files containing any successful tests was most interesting. (Although longer term it might be more interesting based on coverage...)

Things to investigate:

* [ ] The "Reason for failure" table contains entries that look like `missing_definition` and `ioctl`, which is odd. I'd expect one or the other, not both. This needs investigation, as it's probably a bug in how we parse CBMC properties results.
* [ ] Might want to start tracking possible targets for "default stubs" that Kani (or assess) might ship with turned on by default. Started to see some interesting possibilities: clock_gettime, uname, rdtsc, getrlimit, sysconf, __libc_current_sigrtmin

Problems:

* [X] #2108
* [ ] Some crates fail to build with Kani because their workspace also depends on their published crate, which creates an ambiguity: #2104
* [ ] #2112

Standing issues:

* [ ] Performance with MIR linker: #1828
* [ ] Lack of timeouts / assess's use of `unwind(1)`: #1687
* [ ] Common unsupported features: #2107
* [ ] Coverage data
