### ISSUE TITLE
General notes on usability issues revealed by documentation writing

### ISSUE THREAD

**Issue by tedinski** [model-checking/kani#477]
I just wanted to publicly track the things I came across somewhere as I find them, so I don't forget.

Critical (ordered):

* [x] #368 This blocks using visualize (and so blocks getting traces) when unwind is needed
* [x] #493 Blank output is very user-unfriendly
* [x] `cargo-rmc` doesn't really work well (e.g. doesn't handle dependencies), and running rmc and cargo on a crate is currently a magic incantation. #451 
* [x] A release of RMC, so users don't need to build from scratch.
  * Maybe just a brew package for RMC (CBMC has one, but CBMC viewer would also need one) (Or possibly just a cargo crate? `cargo install rmc`?)
* [x] Needing the harness to be unmangled `main` is bothersome, I really think we want something like `#[proof]` #464 
* [x] We need to write these magic declarations for things like `__nondet` that really should be implicitly available already, and really should have more idiomatic names. We should have an RMC prelude that gives us `rmc::assume` and `rmc::nondet` etc.

High (unordered)

* [x] MIR gives us a lot of generated variables that are mostly just copies and obfuscate traces. (e.g. `var_10 = 0;` then `x = var_10;`)
* [ ] There should be a "simpler" version of traces for the common case of "just tell me the nondet values in my proof harness"
* [ ] Possibly some "test case reduction" though this would be a CBMC feature. We get traces about `(534, 535)` that could have been `(0, 1)`

Medium

* [x] "Assertion failed: blah: SUCCESS" is confusing. Failed...Success? #189 
* [x] We should preserve color-coded output of rustc and cbmc. We also need to "stream" output instead of waiting until completion (for instance, to see log lines as they are printed when cbmc doesn't terminate.) I believe this is the same issue. We should connect the 'tty' instead of capturing output as a string and re-printing. 
* [ ] We should be able to annotate individual loops with an `unwind` bound instead of having to resort to a global bound.
* [x] A better summary view on the command line. Needing to `| grep FAIL` is not a good user experience. We should summarize failures at the end of a run. (CBMC task?)
* [x] Can we prioritize (even heuristically) the failures in the output? Helping users understand what they should debug first is a good idea.
* [x] Can we deal with unreachable assertions? Currently these will just report success, but maybe that wasn't intended. (Coverage debugging problem?)
* [x] Visualize should also give good output on the command line, not just dump useless xml. (CBMC/viewer task?)

**Comment by avanhatt** [comment]
Re: point 3, previously filed this similar one: https://github.com/model-checking/rmc/issues/189

**Comment by tedinski** [comment]
I think this one remaining item still has value: 

> There should be a "simpler" version of traces for the common case of "just tell me the nondet values in my proof harness"

But otherwise this tracking issue is largely complete and no longer useful. Closing.
