### ISSUE TITLE
Review failing examples & add flags to them if it proceeds

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#553]
There are 98 failing examples after adding the `trim-diagnostic-paths=no` flag to the list of flags (this is missing in the dashboard code). We should review these examples before #517 and add flags that make them pass if possible. The list of examples is:

- [x] `Rust by Example/Conversion/To and from Strings/10.rs` - known issue #241  
- [x] `Rust by Example/Conversion/To and from Strings/41.rs` - known issue #241 + overflow
- [x] `Rust by Example/Custom Types/Enums/Testcase: linked-list/5.rs` - multiple memory safety failures
- [x] `Rust by Example/Error handling/Iterating over Results/22.rs` - #556 
- [x] `Rust by Example/Error handling/Iterating over Results/39.rs` - #556
- [x] `Rust by Example/Error handling/Iterating over Results/5.rs` - #556
- [x] `Rust by Example/Error handling/Iterating over Results/54.rs` - #556
- [x] `Rust by Example/Error handling/Iterating over Results/69.rs` - #556 & takes a long time to verify with `--unwind 4 --object-bits 10`
- [x] `Rust by Example/Error handling/Multiple error types/Boxing errors/11.rs` - #558
- [x] `Rust by Example/Error handling/Multiple error types/Defining an error type/18.rs` - #558
- [x] `Rust by Example/Error handling/Multiple error types/Other uses of ?/25.rs` - #558
- [x] `Rust by Example/Error handling/Multiple error types/Pulling Results out of Options/34.rs` - #558
- [x] `Rust by Example/Error handling/Multiple error types/Pulling Results out of Options/6.rs` - #558
- [x] `Rust by Example/Error handling/Multiple error types/Wrapping errors/5.rs` - #558
- [x] `Rust by Example/Error handling/Option & unwrap/Combinators: and_then/15.rs` - #558
- [x] `Rust by Example/Error handling/Option & unwrap/Combinators: map/15.rs` - #558
- [x] `Rust by Example/Error handling/Option & unwrap/Unpacking options with ?/19.rs` - #558
- [x] `Rust by Example/Error handling/Result/64.rs` - #558
- [x] `Rust by Example/Error handling/Result/Early returns/11.rs` - #558
- [x] `Rust by Example/Error handling/Result/Introducing ?/16.rs` - #558
- [x] `Rust by Example/Error handling/Result/Introducing ?/46.rs` - #558
- [x] `Rust by Example/Error handling/Result/aliases for Result/14.rs` - #558
- [x] `Rust by Example/Error handling/Result/map for Result/15.rs` - #558
- [x] `Rust by Example/Error handling/Result/map for Result/54.rs` - #558
- [x] `Rust by Example/Flow of Control/for and range/63.rs` takes a long time to verify with `--unwind 4 --object-bits 10`, and `--unwind 4` is not enough
- [x] `Rust by Example/Functions/13.rs`
- [x] `Rust by Example/Functions/Closures/Examples in std/Iterator::any/22.rs` #559
- [x] `Rust by Example/Functions/Closures/Examples in std/Searching through iterators/22.rs` #559
- [x] `Rust by Example/Generics/Associated items/Associated types/7.rs` - Warning in 2015 edition, error in 2018
- [x] `Rust by Example/Generics/Phantom type parameters/Testcase: unit clarification/24.rs` #560 
- [x] `Rust by Example/Scoping rules/RAII/11.rs` #561
- [x] `Rust by Example/Std library types/Arc/5.rs` - Concurrent features used
- [x] `Rust by Example/Std library types/HashMap/14.rs` - Unsupported std-lib feature used
- [x] `Rust by Example/Std library types/HashMap/Alternate_custom key types/29.rs` - Unsupported std-lib feature used
- [x] `Rust by Example/Std library types/Strings/118.rs` - May be related to #558 
- [x] `Rust by Example/Std library types/Strings/12.rs`- Needs a higher unwind value but takes too long
- [x] `Rust by Example/Std misc/Channels/7.rs` - Concurrent features used
- [x] `Rust by Example/Std misc/File I_O/read lines/9.rs` - I/O features used, needs a higher unwind value but takes too long
- [x] `Rust by Example/Std misc/Path/15.rs` - #563
- [x] `Rust by Example/Std misc/Program arguments/8.rs` - Arguments used, needs a higher unwind value but takes too long
- [x] `Rust by Example/Std misc/Program arguments/Argument parsing/5.rs` - Arguments used, needs a higher unwind value but takes too long
- [x] `Rust by Example/Std misc/Threads/6.rs` - Concurrent features used
- [x] `Rust by Example/Std misc/Threads/Testcase: map-reduce/24.rs` - Concurrent features used
- [x] `Rust by Example/Traits/Derive/16.rs` - #558 
- [x] `Rust by Example/Traits/Disambiguating overlapping traits/11.rs` - #564
- [x] `Rust by Example/Traits/impl Trait/6.rs` - May be related to #559 
- [x] `Rust by Example/Traits/impl Trait/64.rs`
- [x] `The Rust Reference/Appendices/Glossary/263.rs`
- [x] `The Rust Reference/Items/Use declarations/37.rs` - Unsupported std-lib feature used
- [x] `The Rust Reference/Linkage/190.rs` - Env variables used, needs a higher unwind value but takes too long
- [x] `The Rust Reference/Macros/48.rs` - CBMC invariant violation as in #479 
- [x] `The Rust Reference/Patterns/367.rs`
- [x] `The Rust Reference/Statements and expressions/Expressions/125.rs` - #559 
- [x] `The Rust Reference/Statements and expressions/Expressions/Grouped expressions/27.rs` - #274 
- [x] `The Rust Reference/Statements and expressions/Expressions/Method call expressions/10.rs` - Maybe #558 
- [x] `The Rust Reference/Statements and expressions/Expressions/Operator expressions/108.rs` - Maybe #556 
- [x] `The Rust Reference/Statements and expressions/Expressions/Operator expressions/263.rs` - #558 
- [x] `The Rust Reference/Type system/Types/113.rs`
- [x] `The Rust Reference/Type system/Types/Closure types/137.rs` - #274 
- [x] `The Rust Reference/Type system/Types/Trait object types/71.rs`
- [x] `The Rustonomicon/Concurrency/Races/30.rs`
- [x] `The Rustonomicon/Concurrency/Races/61.rs`
- [x] `The Rustonomicon/Data Layout/Exotically Sized Types/47.rs` - #566
- [x] `The Rustonomicon/Implementing Vec/Final Code/3.rs` - Maybe #78 
- [x] `The Unstable Book/Compiler Flags/sanitizer/198.rs` - The example is supposed to error with a sanitizer
- [x] `The Unstable Book/Compiler Flags/sanitizer/344.rs` - Concurrent features used
- [x] `The Unstable Book/Compiler Flags/sanitizer/53.rs` - The example is supposed to error with a sanitizer
- [x] `The Unstable Book/Language Features/generators/165.rs` - #416 
- [x] `The Unstable Book/Language Features/generators/28.rs` - #416
- [x] `The Unstable Book/Language Features/generators/60.rs` - #416
- [x] `The Unstable Book/Language Features/trait_alias/14.rs` - #567
- [x] `The Unstable Book/Language Features/try_blocks/12.rs` - #558 
- [x] `The Unstable Book/Language Features/unsized_locals/13.rs` - #568
- [x] `The Unstable Book/Language Features/unsized_locals/153.rs` - #568
- [x] `The Unstable Book/Language Features/unsized_locals/164.rs` - #568
- [x] `The Unstable Book/Language Features/unsized_locals/88.rs` - #568
- [x] `The Unstable Book/Language Features/unsized_tuple_coercion/17.rs` - #568
- [x] `The Unstable Book/Library Features/asm/119.rs` - #2
- [x] `The Unstable Book/Library Features/asm/133.rs` - #2
- [x] `The Unstable Book/Library Features/asm/155.rs` - #2
- [x] `The Unstable Book/Library Features/asm/176.rs` - #2
- [x] `The Unstable Book/Library Features/asm/194.rs` - #2
- [x] `The Unstable Book/Library Features/asm/242.rs` - #2
- [x] `The Unstable Book/Library Features/asm/272.rs` - #2
- [x] `The Unstable Book/Library Features/asm/332.rs` - #2
- [x] `The Unstable Book/Library Features/asm/380.rs` - #2
- [x] `The Unstable Book/Library Features/asm/40.rs` - #2
- [x] `The Unstable Book/Library Features/asm/417.rs` - #2
- [x] `The Unstable Book/Library Features/asm/57.rs` - #2
- [x] `The Unstable Book/Library Features/asm/79.rs` - #2
- [x] `The Unstable Book/Library Features/format_args_capture/14.rs` - #569
- [x] `The Unstable Book/Library Features/format_args_capture/28.rs` - #569
- [x] `The Unstable Book/Library Features/llvm_asm/135.rs` - #2
- [x] `The Unstable Book/Library Features/llvm_asm/169.rs` - #2
- [x] `The Unstable Book/Library Features/llvm_asm/33.rs` - #2
- [x] `The Unstable Book/Library Features/llvm_asm/59.rs` - #2
- [x] `The Unstable Book/Library Features/llvm_asm/75.rs` - #2
- [x] `The Unstable Book/Library Features/llvm_asm/91.rs` - #2

Checks here mean that they have been reviewed - the actual fix will come in a later PR.

**Comment by adpaco-aws** [comment]
Marking this as blocked because of #581
