### ISSUE TITLE
Intrinsics Audit

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#727]
The intrinsics list below is based on the table recently published in #714.

The goal is for each intrinsics to:
1. Identify what is needed to claim full support.
2. Implement support for it if possible.

Note: We are now focusing on fixing issues with intrinsics that we already support. New intrinsics will be added on demand.

This issue will keep track of the work done on intrinsics (a check on intrinsics will mark it as "done") and link other issues related to the implementation/rework/cleanup of intrinsics.

 - [x] `abort`: Handled separately as non returning intrinsic.
 - [x] `add_with_overflow`: Reviewed and tested in #1083 
 - [x] `arith_offset`: Disabled in #1081 
 - [x] `assert_inhabited`: Changed to emit a panic or no-op depending on type.
 - [x] `assert_uninit_valid`: Changed to emit a panic or no-op depending on type.
 - [x] `assert_zero_valid`: Changed to emit a panic or no-op depending on type.
 - [x] `assume`: Added two tests in #1015 
 - [x] `atomic_and`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_and_acq`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_and_acqrel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_and_rel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_and_relaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchg`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchg_acq`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchg_acq_failrelaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchg_acqrel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchg_acqrel_failrelaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchg_failacq`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchg_failrelaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchg_rel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchg_relaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchgweak`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchgweak_acq`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchgweak_acq_failrelaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchgweak_acqrel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchgweak_acqrel_failrelaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchgweak_failacq`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchgweak_failrelaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchgweak_rel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_cxchgweak_relaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_fence`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_fence_acq`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_fence_acqrel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_fence_rel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_load`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_load_acq`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_load_relaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_load_unordered`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_max`: Unimplemented. Negative tests added in #850
 - [x] `atomic_max_acq`: Unimplemented. Negative tests added in #850
 - [x] `atomic_max_acqrel`: Unimplemented. Negative tests added in #850
 - [x] `atomic_max_rel`: Unimplemented. Negative tests added in #850
 - [x] `atomic_max_relaxed`: Unimplemented. Negative tests added in #850
 - [x] `atomic_min`: Unimplemented. Negative tests added in #850
 - [x] `atomic_min_acq`: Unimplemented. Negative tests added in #850
 - [x] `atomic_min_acqrel`: Unimplemented. Negative tests added in #850
 - [x] `atomic_min_rel`: Unimplemented. Negative tests added in #850
 - [x] `atomic_min_relaxed`: Unimplemented. Negative tests added in #850
 - [x] `atomic_nand`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_nand_acq`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_nand_acqrel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_nand_rel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_nand_relaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_or`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_or_acq`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_or_acqrel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_or_rel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_or_relaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_singlethreadfence`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_singlethreadfence_acq`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_singlethreadfence_acqrel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_singlethreadfence_rel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_store`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_store_rel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_store_relaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_store_unordered`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_umax`: Unimplemented. Negative tests added in #850
 - [x] `atomic_umax_acq`: Unimplemented. Negative tests added in #850
 - [x] `atomic_umax_acqrel`: Unimplemented. Negative tests added in #850
 - [x] `atomic_umax_rel`: Unimplemented. Negative tests added in #850
 - [x] `atomic_umax_relaxed`: Unimplemented. Negative tests added in #850
 - [x] `atomic_umin`: Unimplemented. Negative tests added in #850
 - [x] `atomic_umin_acq`: Unimplemented. Negative tests added in #850
 - [x] `atomic_umin_acqrel`: Unimplemented. Negative tests added in #850
 - [x] `atomic_umin_rel`: Unimplemented. Negative tests added in #850
 - [x] `atomic_umin_relaxed`: Unimplemented. Negative tests added in #850
 - [x] `atomic_xadd`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xadd_acq`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xadd_acqrel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xadd_rel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xadd_relaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xchg`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xchg_acq`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xchg_acqrel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xchg_rel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xchg_relaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xor`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xor_acq`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xor_acqrel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xor_rel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xor_relaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xsub`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xsub_acq`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xsub_acqrel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xsub_rel`: Reviewed in #850. Possible improvement: #25
 - [x] `atomic_xsub_relaxed`: Reviewed in #850. Possible improvement: #25
 - [x] `bitreverse`: Support added in #779 and testing enabled in #926.
 - [x] `blackbox`: No action needed, both implementation and test look good.
 - [x] `breakpoint`: Added a test in #1022 
 - [x] `bswap`: Added a test in #1023 
 - [x] `caller_location`: Unimplemented (see #374)
 - [x] `ceilf32`: Unimplemented (was disabled in #1026).
 - [x] `ceilf64`: Unimplemented (was disabled in #1026).
 - [x] `copy`: Disabled in #1081 
 - [x] `copy_nonoverlapping`: Disabled in #1081
 - [x] `copysignf32`: Disabled in #1081
 - [x] `copysignf64`: Disabled in #1081
 - [x] `cosf32`: Added test in #1043 
 - [x] `cosf64`: Added test in #1043 
 - [x] `ctlz`: Reviewed and completed testing in #883 
 - [x] `ctlz_nonzero`: Reviewed and completed testing in #883 
 - [x] `ctpop`: Completed testing in #1048 
 - [x] `cttz`: Reviewed and completed testing in #883 
 - [x] `cttz_nonzero`: Reviewed and completed testing in #883 
 - [x] `discriminant_value`: Test added in #1021 
 - [x] `drop_in_place`: Unimplemented (deprecated since 1.52 in favor of `std::ptr::drop_in_place`)
 - [x] `exact_div`: Added tests for all corner cases in #1007 
 - [x] `exp2f32`: Disabled in #1081
 - [x] `exp2f64`: Disabled in #1081
 - [x] `expf32`: Disabled in #1081
 - [x] `expf64`: Disabled in #1081
 - [x] `fabsf32`: Added tests in #1033 
 - [x] `fabsf64`: Added tests in #1033 
 - [x] `fadd_fast`: Was implemented in #804
 - [x] `fdiv_fast`: Was implemented in #804. Testing can be improved (see #809)
 - [x] `float_to_int_unchecked`: Unimplemented.
 - [x] `floorf32`: Unimplemented (was disabled in #1026).
 - [x] `floorf64`: Unimplemented (was disabled in #1026).
 - [x] `fmaf32`: Disabled in #1081
 - [x] `fmaf64`: Disabled in #1081
 - [x] `fmul_fast`: Was implemented in #804. Testing can be improved (see #809)
 - [x] `forget`: Added comment and tests in #1041 
 - [x] `frem_fast`: Unimplemented (see #810)
 - [x] `fsub_fast`: Was implemented in #804
 - [x] `likely`: Added a test in #851 
 - [x] `log2f32`: Disabled in #1081
 - [x] `log2f64`: Disabled in #1081
 - [x] `log10f32`: Disabled in #1081
 - [x] `log10f64`: Disabled in #1081
 - [x] `logf32`: Disabled in #1081
 - [x] `logf64`: Disabled in #1081
 - [x] `maxnumf32`: Disabled in #1081
 - [x] `maxnumf64`: Disabled in #1081
 - [x] `min_align_of`: Implementation is constant-evaluated, added test in #1042 
 - [x] `min_align_of_val`: Reviewed and added tests in #1101 and #1089 
 - [x] `minnumf32`: Disabled in #1081
 - [x] `minnumf64`: Disabled in #1081
 - [x] `move_val_init`: Unimplemented.
 - [x] `mul_with_overflow`: Reviewed and tested in #1083 
 - [x] `nearbyintf32`: Unimplemented (was disabled in #1028).
 - [x] `nearbyintf64`: Unimplemented (was disabled in #1028).
 - [x] `needs_drop`: Implementation is constant-evaluated, added test in #1042 
 - [x] `nontemporal_store`: Unimplemented.
 - [x] `offset`: Reviewed in #1094 
 - [x] `powf32`: Disabled in #1081
 - [x] `powf64`: Disabled in #1081
 - [x] `powif32`: Disabled in #1081
 - [x] `powif64`: Disabled in #1081
 - [x] `pref_align_of`: Implementation is constant-evaluated, added test in #1042 
 - [x] `prefetch_read_data`: Unimplemented.
 - [x] `prefetch_read_instruction`: Unimplemented.
 - [x] `prefetch_write_data`: Unimplemented.
 - [x] `prefetch_write_instruction`: Unimplemented.
 - [x] `ptr_guaranteed_eq`: Reviewed and added tests in #1090 
 - [x] `ptr_guaranteed_ne`: Reviewed and added tests in #1090 
 - [x] `ptr_offset_from`: Reviewed and added tests in #1099 
 - [x] `raw_eq`: Reviewed and documented in #1091 
 - [x] `rintf32`: Unimplemented (was disabled in #1028).
 - [x] `rintf64`: Unimplemented (was disabled in #1028).
 - [x] `rotate_left`: Improved testing in #880.
 - [x] `rotate_right`: Improved testing in #880.
 - [x] `roundf32`: Unimplemented (was disabled in #1026).
 - [x] `roundf64`: Unimplemented (was disabled in #1026).
 - [x] `rustc_peek`: Unimplemented.
 - [x] `saturating_add`: Improved testing in #853. Consider #852 in the future.
 - [x] `saturating_sub`: Improved testing in #853. Consider #852 in the future.
 - [x] `sinf32`: Added test in #1043 
 - [x] `sinf64`: Added test in #1043 
 - [x] `size_of`: Implementation is constant-evaluated, added test in #1042 
 - [x] `size_of_val`: Reviewed and added tests in #1101 and #1089 
 - [x] `sqrtf32`: Disabled in #1081
 - [x] `sqrtf64`: Disabled in #1081
 - [x] `sub_with_overflow`: Reviewed and tested in #1083 
 - [x] `transmute`: Handled separately as non returning intrinsic (missing case) in #736. Added tests for the general case in #1104 
 - [x] `truncf32`: Unimplemented (was disabled in #1028).
 - [x] `truncf64`: Unimplemented (was disabled in #1028).
 - [x] `try`: Unimplemented ("fixme" test is included) in #267 
 - [x] `type_id`: Implementation is constant-evaluated, added test in #1042 
 - [x] `type_name`: Implementation is constant-evaluated, added test in #1042 
 - [x] `unaligned_volatile_load`: Disabled in #1081
 - [x] `unaligned_volatile_store`: Unimplemented.
 - [x] `unchecked_add`: Reviewed and added tests in #1076 
 - [x] `unchecked_div`: Reviewed and added tests in #1076 
 - [x] `unchecked_mul`: Reviewed and added tests in #1076 
 - [x] `unchecked_rem`: Reviewed and added tests in #1076 
 - [x] `unchecked_shl`: Reviewed and added tests in #1076 
 - [x] `unchecked_shr`: Reviewed and added tests in #1076 
 - [x] `unchecked_sub`: Reviewed and added tests in #1076 
 - [x] `unlikely`: Added a test in #851 
 - [x] `unreachable`: Removed implementation (as it was handled by `TerminatorKind::Unreachable`) and added tests in #1100 
 - [x] `variant_count`: Unimplemented. Added negative and fixme tests in #854 
 - [x] `volatile_copy_memory`: Disabled in #1081. Should include test for overlapping regions.
 - [x] `volatile_copy_nonoverlapping_memory`:
 - [x] `volatile_load`: Disabled in #1081. Has to ensure `src` is properly initialized.
 - [x] `volatile_set_memory`: Unimplemented.
 - [x] `volatile_store`: Added a concurrency warning, an alignment check and two new tests.
 - [x] `wrapping_add`: Was reviewed in #647. Added test in #1070.
 - [x] `wrapping_mul`: Was reviewed in #647. Added test in #1070.
 - [x] `wrapping_sub`: Was reviewed in #647. Added test in #1070.
 - [x] `write_bytes`: Reviewed and added tests in #1102

**Comment by adpaco-aws** [comment]
Added `abort` (#734) and `transmute` (missing case) which should be handled as non returning intrinsics.

**Comment by adpaco-aws** [comment]
> Added `abort` (#734) and `transmute` (missing case) which should be handled as non returning intrinsics.

These cases were fixed in #738, marking `abort` as done (`transmute` still needs auditing for the general case).

**Comment by adpaco-aws** [comment]
Added `assert_inhabited`. Marked `assert_inhabited`, `assert_uninit_valid` and `assert_zero_valid` after merging #742

**Comment by adpaco-aws** [comment]
Created #788 for fast math intrinsics. A first attempt was made in [this branch](https://github.com/adpaco-aws/rmc/tree/fast-math) but there are some issues with this approach that require some guidance from CBMC experts.

**Comment by adpaco-aws** [comment]
Updated to reflect status after merging #804

**Comment by adpaco-aws** [comment]
Marked `volatile_store` as done since its audit was completed in #794

**Comment by adpaco-aws** [comment]
Basically, the remaining intrinsics to be audited can be classified into 3 groups:
 1. `wrapping_<op>`, `unchecked_op` and `<op>_with_overflow`, which were reviewed and tested in #647 
 2. Math-related intrinsics that just need a single test.
 3. Others (notably, volatile and pointer-related ones)
The plan is to audit (1) first, then focus on (3) and leave (2) for the last ones.

**Comment by adpaco-aws** [comment]
The audit has been completed and all intrinsics in the list have been reviewed.

There is a small amount of remaining cleanup work to be done which is going to be tracked in the following issues:
 * #1115 
 * #1116
 * #789

**Comment by adpaco-aws** [comment]
The audit has been completed and all intrinsics in the list have been reviewed.

There is a small amount of remaining cleanup work to be done which is going to be tracked in the following issues:
 * #1115 
 * #1116
 * #789
