### ISSUE TITLE
Documentation: Remaining tasks

### ISSUE THREAD

**Issue by adpaco-aws** [model-checking/kani#970]
Will keep adding stuff that cannot be done now (during #700 ) but has to be done.

- [x] Update project status (in introduction)
- [x] ~~Update project status (in `README.md`)~~ (project status doesn't appear in `README.md`)
- [x] Review installation guide
- [x] Make edits to "Usage - On a package" once #962 is complete.
- [x] Review wording in "Limitations"
- [x] Consider if other topics should appear in "Rust feature support"

**Comment by adpaco-aws** [comment]
After #1160 all tasks have been completed.
